create table product_analytics.client_fact
(client_id varchar(500)
,clienttype varchar(500)
,application_no varchar(500)
,partycode_gendate date
,activefrom date
,email_id varchar(500)
,mobile varchar(500)
,clientname varchar(500)
,age bigint
,age_bucket varchar(500)
,city_kyc varchar(500)
,city_appsflyer varchar(500)
,state_kyc varchar(500)
,state_appsflyer varchar(500)
,country_kyc varchar(500)
,country_appsflyer varchar(500)
,operator varchar(500)
,wifi varchar(500)
,l1_tags varchar(500)
,l2_tags varchar(500)
,kyc_type varchar(500)
,diy varchar(500)
,diy_type varchar(500)
,eq_portfolio_total_scrips bigint
,eq_portfolio_investment_value bigint
,eq_portfolio_current_value bigint
,clientinactivefrom date
,activeoneq date
,inactivefromeq date
,activeoncomm date
,inactivefromcomm date
,activeoncurr date
,inactivefromcurr date
,activeonfno date
,inactivefromfo date
,datefirstfundadded date
,datelastfundadded date
,datelastfundwithdraw date
,addfund_last30_days bigint
,addfund_last60_days bigint
,addfund_last90_days bigint
,datefirsttrade date
,datelasttrade date
,tradedwithindays varchar(500)
,traded_bucket varchar(500)
,totaltradevalue bigint
,firsttradevalue bigint
,delivery_oc_last30days bigint
,delivery_oc_last60days bigint
,delivery_oc_last90days bigint
,fno_oc_last30days bigint
,fno_oc_last60days bigint
,fno_oc_last90days bigint
,intraday_oc_last30days bigint
,intraday_oc_last60days bigint
,intraday_oc_last90days bigint
,commodity_oc_last30days bigint
,commodity_oc_last60days bigint
,commodity_oc_last90days bigint
,currency_oc_last30days bigint
,currency_oc_last60days bigint
,currency_oc_last90days bigint
,delivery_turnover_last30days bigint
,delivery_turnover_last60days bigint
,delivery_turnover_last90days bigint
,fno_turnover_last30days bigint
,fno_turnover_last60days bigint
,fno_turnover_last90days bigint
,intraday_turnover_last30days bigint
,intraday_turnover_last60days bigint
,intraday_turnover_last90days bigint
,commodity_turnover_last30days bigint
,commodity_turnover_last60days bigint
,commodity_turnover_last90days bigint
,currency_turnover_last30days bigint
,currency_turnover_last60days bigint
,currency_turnover_last90days bigint
,delivery_brokerage_last30days bigint
,delivery_brokerage_last60days bigint
,delivery_brokerage_last90days bigint
,fno_brokerage_last30days bigint
,fno_brokerage_last60days bigint
,fno_brokerage_last90days bigint
,intraday_brokerage_last30days bigint
,intraday_brokerage_last60days bigint
,intraday_brokerage_last90days bigint
,commodity_brokerage_last30days bigint
,commodity_brokerage_last60days bigint
,commodity_brokerage_last90days bigint
,currency_brokerage_last30days bigint
,currency_brokerage_last60days bigint
,currency_brokerage_last90days bigint
,datefirsttradeequity date
,datelasttradeequity date
,datefirsttradefno date
,datelasttradefno date
,datefirsttradecurr date
,datelasttradecurr date
,datefirsttradecomm date
,datelasttradecomm date
,totalmfordercount bigint
,mfportfoliovalue bigint
,datefirsttrademf date
,datelasttrademf date
,totalsgbordercount bigint
,datefirsttradesgb date
,datelasttradesgb date
,totaluniqueipoapplied1yr bigint
,totalipoapplied1yr bigint
,datefirstipoapplied date
,datelastipoapplied date
,totalgttordercount bigint
,datefirstgttorder date
,datelastgttorder date
,stocksipordercount bigint
,datefirstsiporder date
,datelastsiporder date
,total_nps_response bigint
,detractor bigint
,promoter bigint
,total_nps_response_portfolio bigint
,total_nps_response_ipo bigint
,total_nps_response_charts bigint
,total_nps_response_addfunds bigint
,total_nps_response_orders bigint
,total_nps_response_kyc bigint
,spark_android_network_type varchar(500)
,abma_android_network_type varchar(500)
,spark_ios_network_type varchar(500)
,abma_ios_network_type varchar(500)
,spark_android_device_model varchar(500)
,abma_android_device_model varchar(500)
,spark_ios_device_model varchar(500)
,spark_web_device_model varchar(500)
,tab_device_model varchar(500)
,abma_ios_device_model varchar(500)
,first_login date
,abma_android_first_login date
,abma_ios_first_login date
,spark_android_first_login date
,spark_ios_first_login date
,tab_first_login date
,spark_web_first_login date
,abmaandroid_last_login date
,abmaios_last_login date
,sparkandroid_last_login date
,sparkios_last_login date
,tab_last_login date
);